export { HomePage } from "./Home"
export { LoginPage } from "./Login"
export { RegisterPage } from "./Register"
export { DashboardPage } from "./Dashboard"
export { DesignSystemPage } from "./DesignSystem"
